[build]
builder = "nixpacks"
buildCommand = ""

[deploy]
startCommand = "gunicorn backend:app"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[experimental]
persistMode = "file"